DROP TABLE IF EXISTS PRICE;

CREATE TABLE PRICE (
    id INTEGER NOT NULL AUTO_INCREMENT,
    brand_id INTEGER NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    price_list INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,

    PRIMARY KEY (id)
);